#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nbeny <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/07 21:11:22 by nbeny             #+#    #+#              #
#    Updated: 2017/02/17 11:12:11 by nbeny            ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME	=	libft.a

SRCS	=	ft_memset.c ft_bzero.c ft_memcpy.c ft_memccpy.c\
		ft_memmove.c ft_memchr.c ft_memcmp.c\
		ft_strlen.c ft_strdup.c	ft_strcpy.c ft_strncpy.c\
		ft_strcat.c ft_strncat.c ft_strlcat.c ft_strchr.c\
		ft_strrchr.c ft_strstr.c ft_strnstr.c ft_strcmp.c\
		ft_strncmp.c\
		ft_atoi.c ft_isalpha.c ft_isdigit.c ft_isalnum.c\
		ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c\
		ft_memalloc.c ft_memdel.c\
		ft_strnew.c ft_strdel.c ft_strclr.c ft_striter.c\
		ft_striteri.c ft_strmap.c ft_strmapi.c ft_strequ.c\
		ft_strnequ.c ft_strsub.c ft_strjoin.c ft_strtrim.c\
		ft_strsplit.c\
		ft_itoa.c ft_itoa_base.c ft_litoa_base.c ft_uitoa_base.c\
		ft_ulitoa_base.c ft_max_itoa_base.c ft_umax_itoa_base.c\
		ft_size_itoa_base.c ft_short_itoa_base.c ft_ushort_itoa_base.c\
		ft_char_itoa_base.c ft_uchar_itoa_base.c ft_llitoa_base.c\
		ft_ullitoa_base.c\
		ft_putchar.c ft_putstr.c ft_putendl.c ft_putnbr.c\
		ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c\
		ft_max.c ft_min.c ft_sort_integer_tab.c ft_sort_params.c\
		ft_sqrt.c\
		ft_putcstr.c ft_capitalizer.c ft_rotcstring.c ft_putnstr.c\
		ft_short_putnbr_base.c ft_ushort_putnbr_base.c ft_char_putnbr_base.c\
		ft_uchar_putnbr_base.c ft_putnbr_base.c ft_uputnbr_base.c\
		ft_lputnbr_base.c ft_ulputnbr_base.c ft_llputnbr_base.c\
		ft_ullputnbr_base.c ft_max_putnbr_base.c ft_umax_putnbr_base.c\
		ft_size_putnbr_base.c ft_power.c\
		ft_wbytelen.c ft_wcharlen.c ft_wstrlen.c

OBJS	=	ft_memset.o ft_bzero.o ft_memcpy.o ft_memccpy.o\
		ft_memmove.o ft_memchr.o ft_memcmp.o\
		ft_strlen.o ft_strdup.o	ft_strcpy.o ft_strncpy.o\
		ft_strcat.o ft_strncat.o ft_strlcat.o ft_strchr.o\
		ft_strrchr.o ft_strstr.o ft_strnstr.o ft_strcmp.o\
		ft_strncmp.o\
		ft_atoi.o ft_isalpha.o ft_isdigit.o ft_isalnum.o\
		ft_isascii.o ft_isprint.o ft_toupper.o ft_tolower.o\
		ft_memalloc.o ft_memdel.o\
		ft_strnew.o ft_strdel.o ft_strclr.o ft_striter.o\
		ft_striteri.o ft_strmap.o ft_strmapi.o ft_strequ.o\
		ft_strnequ.o ft_strsub.o ft_strjoin.o ft_strtrim.o\
		ft_strsplit.o\
		ft_itoa.o ft_itoa_base.o ft_litoa_base.o ft_uitoa_base.o\
		ft_ulitoa_base.o ft_max_itoa_base.o ft_umax_itoa_base.o\
		ft_size_itoa_base.o ft_short_itoa_base.o ft_ushort_itoa_base.o\
		ft_char_itoa_base.o ft_uchar_itoa_base.o ft_llitoa_base.o\
		ft_ullitoa_base.o\
		ft_putchar.o ft_putstr.o ft_putendl.o ft_putnbr.o\
		ft_putchar_fd.o ft_putstr_fd.o ft_putendl_fd.o ft_putnbr_fd.o\
		ft_max.o ft_min.o ft_sort_integer_tab.o ft_sort_params.o\
		ft_sqrt.o\
		ft_putcstr.o ft_capitalizer.o ft_rotcstring.o ft_putnstr.o\
		ft_short_putnbr_base.o ft_ushort_putnbr_base.o ft_char_putnbr_base.o\
		ft_uchar_putnbr_base.o ft_putnbr_base.o ft_uputnbr_base.o\
		ft_lputnbr_base.o ft_ulputnbr_base.o ft_llputnbr_base.o\
		ft_ullputnbr_base.o ft_max_putnbr_base.o ft_umax_putnbr_base.o\
		ft_size_putnbr_base.o ft_power.o\
		ft_wbytelen.o ft_wcharlen.o ft_wstrlen.o

HDRS	=	libft.h

FLAGS	=	-Wall -Wextra -Werror

all: $(NAME)

$(NAME):
		gcc $(FLAGS) -c $(SRCS) -I $(HDRS)
		ar rc $(NAME) $(OBJS)
		ranlib $(NAME)

clean:
		rm -f $(OBJS)

fclean: clean
		rm -f $(NAME)

re: fclean all
